### ISSUE TITLE
加外來人口統一證號編碼

### ISSUE THREAD

**Issue by fifieldt** [enylin/taiwan-id-validator#1]
https://www.immigration.gov.tw/media/20493/%E5%A4%96%E4%BE%86%E4%BA%BA%E5%8F%A3%E7%B5%B1%E4%B8%80%E8%AD%89%E8%99%9F%E7%B7%A8%E7%A2%BC%E5%8E%9F%E5%89%87.pdf

**Comment by enylin** [comment]
Can you provide the English translation of 外來人口統一證號?

**Comment by fifieldt** [comment]
Hi, sorry - I thought you might prefer Chinese - standby while I translate :)

**Comment by fifieldt** [comment]
"外來人口統一證號" is how the government groups residents of Taiwan who have IDs, but not household registration. This includes:
* Taiwanese nationals without household registration
* Legal residents from the Mainland, Hong Kong, Macao, & other countries (who can't get household registration, but are allowed to live in Taiwan)

The format of the card is the same as for Taiwan National ID, except the second number (used for male/female) becomes a letter. So, the format is:
* 2 English Letters, followed by 8 numbers
* 1st letter is the same as Taiwanese ID - the location of registration
* 2nd letter is for male/female. It's either A or C for male or B or D for female
* 8 numbers

A good name for the function might be isResidentIdentificationNumberValid(), but you're in charge!

**Comment by enylin** [comment]
Hi, thank you for translating the whole thing! I actually just meant the phrase itself, but having the explanation in English will definitely be more helpful to the non-Chinese speaking community, especially in this issue. 

As for the naming of the function, I want to be more specific so as to differentiate between 外來人口統一證號 and regular ID. I propose isAlienResidentCertificateNumberValid which is also applicable for APRCs. It's not perfect because ARCs only apply to the foreign population, but since they are they are the ones to which this function most applies and I have yet to find an official translation, this will do for now.

References:
https://www.taiwannews.com.tw/en/news/3563120
https://www.ntbsa.gov.tw/etwmain/download?sid=13adf44d84b00000b68d6bb251fa309a

**Comment by fifieldt** [comment]
No problem, thanks for the code :)

If you want to get down into that level of detail, officially what we end up with is two names: Alien Resident Certificate (外僑居留證) and Taiwan Area Resident Certificate (台灣地區居留證). They both use the same ID number format, but some are held by Taiwanese nationals and others are held by foreign nationals. So ResidentCertificateNumber would probably be more accurate than AlienResidentCertificateNumber if the desire is to capture both. Hope that helps.

**Comment by enylin** [comment]
I've pushed a commit https://github.com/enylin/taiwan-id-validator/commit/eb0ef0c671325fa11c8997fc7460f2117f13087d
But I still need some test cases. Could you provide me with some if you have any on your hand?

**Comment by fifieldt** [comment]
Sure, moment.

**Comment by fifieldt** [comment]
https://github.com/enylin/taiwan-id-validator/pull/2

**Comment by enylin** [comment]
#2 merged.
